version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    rebase-strategy: disabled
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
          - "browserslist"
      eslint:
        patterns:
          - "@eslint-*"
          - "@eslint/*"
          - "eslint-*"
          - "eslint"
      jest:
        patterns:
          - "@jest/"
          - "jest-*"
          - "jest"
          - "@types/jest"
      labforward:
        patterns:
          - "@labforward/*"
